variables:
  CIBW_BUILD: cp36-* cp37-* cp38-*

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astropy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    coverage: codecov

    envs:

    # Code style checks
    # - linux: codestyle

    # All platforms with all dependencies
    - macos: py36-test-alldeps-cov
    - linux: py36-test-alldeps-cov
    - windows: py36-test-alldeps-cov

    # Linux with developer version of dependencies
    - linux: py38-test-devdeps-cov

    # Windows. Linux 32-bit and MacOS X with minimal dependencies and older versions of Astropy
    - macos: py36-test-astropy20-cov
    - linux32: py36-test-astropy30-cov
    - windows: py36-test-astropy40-cov

    # Documentation builds
    - macos: build_docs
    - linux: build_docs
    - macos: build_docs

- template: publish.yml@OpenAstronomy
  parameters:
    test_command: pytest -p no:warnings --pyargs regions
    test_extras: test
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      pypi_connection_name : 'pypi_endpoint'
    targets:
    - sdist
    - wheels_linux
    - wheels_macos
    - wheels_windows
