[build-system]
requires = ['setuptools',
            'setuptools_scm',
            'wheel',
            'cython>=0.29.30',
            'oldest-supported-numpy',
            'extension-helpers']
build-backend = 'setuptools.build_meta'

[tool.isort]
    skip_glob = ['regions/*__init__.py*']
    known_first_party = ['regions']
    use_parentheses = true
