[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "cython==0.29.14",
            "oldest-supported-numpy",
            "extension-helpers"]
build-backend = 'setuptools.build_meta'
