[build-system]
requires = ['setuptools',
            'setuptools_scm>=6.2',
            'cython==0.29.36',
            'numpy<1.26.0b1; python_version<"3.12"',
            'numpy>=1.26.0b1; python_version>="3.12"',
            'extension-helpers']
build-backend = 'setuptools.build_meta'

[tool.isort]
    skip_glob = ['regions/*__init__.py*']
    known_first_party = ['regions']
    use_parentheses = true
